USE restaurant;

ALTER TABLE order_details
ADD CONSTRAINT FOREIGN KEY(food_id) REFERENCES menu(foodid)
ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FOREIGN KEY(order_id) REFERENCES orders(orderno)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE orders
ADD CONSTRAINT FOREIGN KEY (customer_id) REFERENCES customer(cphoneno)
ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FOREIGN KEY (caddress) REFERENCES customer(address)
ON DELETE CASCADE ON UPDATE CASCADE;

